# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11630b665fb14305edf6c307411ba9fd58c33db0465f7ba633e17b9c02f29c350767b1c975c8bbb394c05039b85e709d9354844214621d6a36b29ee9ec534c53

test:
  secret_key_base: 0226ca261417ed592c0cd81a88edaa8ce2e927c0bb9c6c5c4442b9fe5327b3f7d58da7411b1f0aa067622f02082e9432e45b622b8d9041a9548c5438d055d143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
